lab:
  outputs:
    dev:
      account: CMGDXIF-QT58595
      database: DATA226LAB
      private_key_passphrase: "sjsu"
      private_key_path: "{{ env_var('DBT_KEY_PATH') }}"
      role: ACCOUNTADMIN
      schema: ANALYTICS
      threads: 1
      type: snowflake
      user: DATA226STUDY
      warehouse: DATA226HOMEWORK
  target: dev
