lab:
  outputs:
    dev:
      account: CMGDXIF-QT58595
      database: DATA226LAB
      private_key_passphrase: sjsu
      private_key_path: /Users/hellojava/Desktop/SJSU 2026 FALL/DATA 226/Lab/DATA226LabGroup6/keys/rsa_key.p8
      role: ACCOUNTADMIN
      schema: RAW
      threads: 1
      type: snowflake
      user: DATA226STUDY
      warehouse: DATA226HOMEWORK
  target: dev
